// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVc06zbGRxi_Oc3CI0Lt3iiJSLUZi_WBA',
    appId: '1:857868084085:web:1d168dd08b475e2d38693c',
    messagingSenderId: '857868084085',
    projectId: 'kel-1-nekofeed',
    authDomain: 'kel-1-nekofeed.firebaseapp.com',
    storageBucket: 'kel-1-nekofeed.firebasestorage.app',
    measurementId: 'G-TZDVVT2N6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwOKkGcqwGok7yvQBEjpXF9pQNwszsauc',
    appId: '1:857868084085:android:2c1431748feb257838693c',
    messagingSenderId: '857868084085',
    projectId: 'kel-1-nekofeed',
    storageBucket: 'kel-1-nekofeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRhysyoZtveWfKOaVzLhCm6SNr3Jq0LA',
    appId: '1:857868084085:ios:cbf6a72122f4811238693c',
    messagingSenderId: '857868084085',
    projectId: 'kel-1-nekofeed',
    storageBucket: 'kel-1-nekofeed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRhysyoZtveWfKOaVzLhCm6SNr3Jq0LA',
    appId: '1:857868084085:ios:cbf6a72122f4811238693c',
    messagingSenderId: '857868084085',
    projectId: 'kel-1-nekofeed',
    storageBucket: 'kel-1-nekofeed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVc06zbGRxi_Oc3CI0Lt3iiJSLUZi_WBA',
    appId: '1:857868084085:web:4fee9e6072284dae38693c',
    messagingSenderId: '857868084085',
    projectId: 'kel-1-nekofeed',
    authDomain: 'kel-1-nekofeed.firebaseapp.com',
    storageBucket: 'kel-1-nekofeed.firebasestorage.app',
    measurementId: 'G-CKP0TFXNW8',
  );
}
