// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEeptMLBjy_p9Qdw4Q3pidx_juRMkgUrE',
    appId: '1:968550808800:web:75f0b64eca0d74f906a485',
    messagingSenderId: '968550808800',
    projectId: 'nekofeed-67740',
    authDomain: 'nekofeed-67740.firebaseapp.com',
    storageBucket: 'nekofeed-67740.firebasestorage.app',
    measurementId: 'G-S6KKBHQMY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVVnrop7YwAvhDlNLhx2v3myfWurn6KKM',
    appId: '1:968550808800:android:2af2b6ef705e9a4f06a485',
    messagingSenderId: '968550808800',
    projectId: 'nekofeed-67740',
    storageBucket: 'nekofeed-67740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3rs3ea2T2KnTPWjp_KDM9ThUQ__uF8A',
    appId: '1:968550808800:ios:58e258d66dfc149206a485',
    messagingSenderId: '968550808800',
    projectId: 'nekofeed-67740',
    storageBucket: 'nekofeed-67740.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE3rs3ea2T2KnTPWjp_KDM9ThUQ__uF8A',
    appId: '1:968550808800:ios:58e258d66dfc149206a485',
    messagingSenderId: '968550808800',
    projectId: 'nekofeed-67740',
    storageBucket: 'nekofeed-67740.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEeptMLBjy_p9Qdw4Q3pidx_juRMkgUrE',
    appId: '1:968550808800:web:75f0b64eca0d74f906a485',
    messagingSenderId: '968550808800',
    projectId: 'nekofeed-67740',
    authDomain: 'nekofeed-67740.firebaseapp.com',
    storageBucket: 'nekofeed-67740.firebasestorage.app',
    measurementId: 'G-S6KKBHQMY1',
  );

}